"use client"
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import Login from "./login/page"
import "./globals.css";
import {useState} from 'react'
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  const [isLogged, setIsLogged] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#EEE" }}>
       {isLogged ? <Login/>: <Sidebar><Header/>{children}</Sidebar> } 
      </body>
    </html>
  );
}
